#ifndef __renogy_hpp__
#define __renogy_hpp__

#include "modbus.hpp"

#define RENOGY_RATED_INPUT_VOLTAGE			MODBUS_VT_INPUT_CONTACT | 0x3000
#define RENOGY_RATED_INPUT_CURRENT			MODBUS_VT_INPUT_CONTACT | 0x3001
#define RENOGY_RATED_INPUT_POWER			MODBUS_VT_INPUT_CONTACT | 0x3002

#define RENOGY_PV_INPUT_VOLTAGE				MODBUS_VT_INPUT_CONTACT | 0x3100
#define RENOGY_PV_INPUT_CURRENT				MODBUS_VT_INPUT_CONTACT | 0x3101
#define RENOGY_PV_INPUT_POWER				MODBUS_VT_INPUT_CONTACT | 0x3102

#define RENOGY_BATTERY_VOLTAGE				MODBUS_VT_INPUT_CONTACT | 0x3104
#define RENOGY_BATTERY_CHARGING_CURRENT		MODBUS_VT_INPUT_CONTACT | 0x3105
#define RENOGY_BATTERY_STATE_OF_CHARGE		MODBUS_VT_INPUT_CONTACT | 0x311A

#define RENOGY_GENERATED_ENERGY_TODAY_L		MODBUS_VT_INPUT_CONTACT | 0x330C
#define RENOGY_GENERATED_ENERGY_TODAY_H		MODBUS_VT_INPUT_CONTACT | 0x330D
#define RENOGY_GENERATED_ENERGY_MONTH_L		MODBUS_VT_INPUT_CONTACT | 0x330E
#define RENOGY_GENERATED_ENERGY_MONTH_H		MODBUS_VT_INPUT_CONTACT | 0x330F
#define RENOGY_GENERATED_ENERGY_YEAR_L		MODBUS_VT_INPUT_CONTACT | 0x3310
#define RENOGY_GENERATED_ENERGY_YEAR_H		MODBUS_VT_INPUT_CONTACT | 0x3311

#define RENOGY_RTC_MINUTE_SECOND			MODBUS_VT_INPUT_REGISTER | 0x9013
#define RENOGY_RTC_HOUR_DAY					MODBUS_VT_INPUT_REGISTER | 0x9014
#define RENOGY_RTC_MONTH_YEAR				MODBUS_VT_INPUT_REGISTER | 0x9015

#endif

