#ifndef __renogy_hpp__
#define __renogy_hpp__

#include "ModBus.hpp"

#define RENOGY_RATED_INPUT_VOLTAGE          ModBus::VT_INPUT_CONTACT | 0x3000
#define RENOGY_RATED_INPUT_CURRENT          ModBus::VT_INPUT_CONTACT | 0x3001
#define RENOGY_RATED_INPUT_POWER            ModBus::VT_INPUT_CONTACT | 0x3002

#define RENOGY_PV_INPUT_VOLTAGE             ModBus::VT_INPUT_CONTACT | 0x3100
#define RENOGY_PV_INPUT_CURRENT             ModBus::VT_INPUT_CONTACT | 0x3101
#define RENOGY_PV_INPUT_POWER               ModBus::VT_INPUT_CONTACT | 0x3102

#define RENOGY_BATTERY_VOLTAGE              ModBus::VT_INPUT_CONTACT | 0x3104
#define RENOGY_BATTERY_CHARGING_CURRENT     ModBus::VT_INPUT_CONTACT | 0x3105
#define RENOGY_BATTERY_STATE_OF_CHARGE      ModBus::VT_INPUT_CONTACT | 0x311A

#define RENOGY_GENERATED_ENERGY_TODAY_L     ModBus::VT_INPUT_CONTACT | 0x330C
#define RENOGY_GENERATED_ENERGY_TODAY_H     ModBus::VT_INPUT_CONTACT | 0x330D
#define RENOGY_GENERATED_ENERGY_MONTH_L     ModBus::VT_INPUT_CONTACT | 0x330E
#define RENOGY_GENERATED_ENERGY_MONTH_H     ModBus::VT_INPUT_CONTACT | 0x330F
#define RENOGY_GENERATED_ENERGY_YEAR_L      ModBus::VT_INPUT_CONTACT | 0x3310
#define RENOGY_GENERATED_ENERGY_YEAR_H      ModBus::VT_INPUT_CONTACT | 0x3311

#define RENOGY_NET_BATTERY_CURRENT_L        ModBus::VT_INPUT_CONTACT | 0x331B
#define RENOGY_NET_BATTERY_CURRENT_H        ModBus::VT_INPUT_CONTACT | 0x331C

#define RENOGY_RTC_MINUTE_SECOND            ModBus::VT_INPUT_REGISTER | 0x9013
#define RENOGY_RTC_HOUR_DAY                 ModBus::VT_INPUT_REGISTER | 0x9014
#define RENOGY_RTC_MONTH_YEAR               ModBus::VT_INPUT_REGISTER | 0x9015

#endif

